# Nixpacks configuration for Railway deployment with uv

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install uv",
    "uv pip install --system --no-cache -e ."
]

[start]
cmd = "PYTHONPATH=src python -m uvicorn model_comparison.app:app --host 0.0.0.0 --port ${PORT:-8000}"