[build]
builder = "NIXPACKS"

[deploy]
startCommand = "PYTHONPATH=src uvicorn model_comparison.app:app --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
